import { Button } from '@/components/ui/button';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import { Input } from '@/components/ui/input';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import { useSession } from '@/stores/session';
import {
  DdlError,
  FK_ACTIONS,
  type FkAction,
  INDEX_METHODS,
  type IndexMethod,
  type IndexSpec,
  constraintSql,
  createIndexSql,
} from '@shared/pg-ddl';
import type { ConstraintSpec } from '@shared/pg-ddl';
import { useEffect, useMemo, useState } from 'react';
import { CheckRow, FieldLabel } from './structure-parts';
import { fetchTableColumns } from './table-columns';

function toggle(list: string[], item: string, on: boolean): string[] {
  return on ? (list.includes(item) ? list : [...list, item]) : list.filter((x) => x !== item);
}

function ColumnPicker({
  columns,
  value,
  onChange,
}: {
  columns: readonly string[];
  value: string[];
  onChange: (v: string[]) => void;
}) {
  return (
    <div className="max-h-[130px] overflow-auto rounded-[6px] p-1.5 shadow-[inset_0_0_0_1px_var(--wb-separator)]">
      {columns.map((c) => (
        <div key={c} className="flex items-center py-0.5 text-[13px]">
          <CheckRow
            checked={value.includes(c)}
            onChange={(v) => onChange(toggle(value, c, v))}
            className="flex-1"
          >
            <span className="font-mono text-[12px]">{c}</span>
          </CheckRow>
          {value.includes(c) && value.length > 1 && (
            <span className="text-[11px] text-[var(--wb-text-3)]">#{value.indexOf(c) + 1}</span>
          )}
        </div>
      ))}
      {columns.length === 0 && (
        <div className="text-[12px] text-[var(--wb-text-3)]">no columns</div>
      )}
    </div>
  );
}

/** Add index: unique, method, columns, partial WHERE, CONCURRENTLY. */
export function AddIndexDialog({
  open,
  schema,
  table,
  columns,
  onCancel,
  onAdd,
}: {
  open: boolean;
  schema: string;
  table: string;
  columns: readonly string[];
  onCancel: () => void;
  onAdd: (spec: IndexSpec) => void;
}) {
  return (
    <Dialog open={open} onOpenChange={(o) => !o && onCancel()}>
      {open && (
        <AddIndexBody
          schema={schema}
          table={table}
          columns={columns}
          onCancel={onCancel}
          onAdd={onAdd}
        />
      )}
    </Dialog>
  );
}

function AddIndexBody({
  schema,
  table,
  columns,
  onCancel,
  onAdd,
}: {
  schema: string;
  table: string;
  columns: readonly string[];
  onCancel: () => void;
  onAdd: (spec: IndexSpec) => void;
}) {
  const [name, setName] = useState('');
  const [cols, setCols] = useState<string[]>([]);
  const [method, setMethod] = useState<IndexMethod>('btree');
  const [unique, setUnique] = useState(false);
  const [where, setWhere] = useState('');
  const [concurrently, setConcurrently] = useState(false);

  const { spec, check } = useMemo(() => {
    const spec: IndexSpec = {
      name: name.trim() || undefined,
      columns: cols,
      method,
      unique: unique && method === 'btree',
      where: where.trim() || undefined,
      concurrently,
    };
    try {
      return {
        spec,
        check: { sql: createIndexSql(schema, table, spec), problem: null as string | null },
      };
    } catch (err) {
      return {
        spec,
        check: { sql: '', problem: err instanceof DdlError ? err.message : String(err) },
      };
    }
  }, [schema, table, name, cols, method, unique, where, concurrently]);

  return (
    <DialogContent className="max-w-[460px]" data-testid="add-index-dialog">
      <DialogHeader>
        <DialogTitle>Add index</DialogTitle>
        <DialogDescription>
          On {schema}.{table}. Staged until you press Apply.
        </DialogDescription>
      </DialogHeader>
      <div>
        <FieldLabel htmlFor="ix-name">Name (optional)</FieldLabel>
        <Input
          id="ix-name"
          value={name}
          onChange={(e) => setName(e.target.value)}
          placeholder="generated by Postgres"
          spellCheck={false}
        />
      </div>
      <div>
        <FieldLabel>Columns (order matters)</FieldLabel>
        <ColumnPicker columns={columns} value={cols} onChange={setCols} />
      </div>
      <div className="grid grid-cols-2 gap-3">
        <div>
          <FieldLabel htmlFor="ix-method">Method</FieldLabel>
          <Select value={method} onValueChange={(v) => setMethod(v as IndexMethod)}>
            <SelectTrigger id="ix-method" aria-label="Index method">
              <SelectValue />
            </SelectTrigger>
            <SelectContent>
              {INDEX_METHODS.map((m) => (
                <SelectItem key={m} value={m}>
                  {m}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
        </div>
        <div className="flex flex-col justify-end gap-1.5 pb-1 text-[13px]">
          <CheckRow
            checked={unique && method === 'btree'}
            disabled={method !== 'btree'}
            onChange={setUnique}
          >
            Unique
          </CheckRow>
          <CheckRow checked={concurrently} onChange={setConcurrently}>
            CONCURRENTLY
          </CheckRow>
        </div>
      </div>
      <div>
        <FieldLabel htmlFor="ix-where">Partial index condition (WHERE, optional)</FieldLabel>
        <Input
          id="ix-where"
          value={where}
          onChange={(e) => setWhere(e.target.value)}
          placeholder="deleted_at IS NULL"
          spellCheck={false}
          className="font-mono"
        />
      </div>
      {cols.length > 0 && check.problem && (
        <p className="text-[12px] text-destructive">{check.problem}</p>
      )}
      {concurrently && (
        <p className="text-[12px] text-[var(--wb-text-2)]">
          CONCURRENTLY runs on its own, outside the transaction, after the other changes.
        </p>
      )}
      <DialogFooter>
        <Button variant="secondary" onClick={onCancel}>
          Cancel
        </Button>
        <Button
          disabled={cols.length === 0 || check.problem !== null}
          onClick={() => onAdd(spec)}
          data-testid="add-index-submit"
        >
          Stage index
        </Button>
      </DialogFooter>
    </DialogContent>
  );
}

type ConstraintKind = ConstraintSpec['type'];

/** Add PK / unique / check / foreign key. */
export function AddConstraintDialog({
  open,
  schema,
  table,
  columns,
  hasPrimaryKey,
  onCancel,
  onAdd,
}: {
  open: boolean;
  schema: string;
  table: string;
  columns: readonly string[];
  hasPrimaryKey: boolean;
  onCancel: () => void;
  onAdd: (spec: ConstraintSpec) => void;
}) {
  return (
    <Dialog open={open} onOpenChange={(o) => !o && onCancel()}>
      {open && (
        <AddConstraintBody
          schema={schema}
          table={table}
          columns={columns}
          hasPrimaryKey={hasPrimaryKey}
          onCancel={onCancel}
          onAdd={onAdd}
        />
      )}
    </Dialog>
  );
}

function AddConstraintBody({
  schema,
  table,
  columns,
  hasPrimaryKey,
  onCancel,
  onAdd,
}: {
  schema: string;
  table: string;
  columns: readonly string[];
  hasPrimaryKey: boolean;
  onCancel: () => void;
  onAdd: (spec: ConstraintSpec) => void;
}) {
  const info = useSession((s) => s.schema);
  const [kind, setKind] = useState<ConstraintKind>(hasPrimaryKey ? 'unique' : 'primary');
  const [name, setName] = useState('');
  const [cols, setCols] = useState<string[]>([]);
  const [expression, setExpression] = useState('');
  const [refTable, setRefTable] = useState('');
  const [refCols, setRefCols] = useState<string[]>([]);
  const [onDelete, setOnDelete] = useState<FkAction>('NO ACTION');
  const [onUpdate, setOnUpdate] = useState<FkAction>('NO ACTION');

  const tables = useMemo(
    () => (info?.tables ?? []).filter((t) => t.kind === 'table' || t.kind === 'partitioned'),
    [info],
  );
  const refTableInfo = tables.find((t) => `${t.schema}.${t.name}` === refTable);
  const [refColumnNames, setRefColumnNames] = useState<string[]>([]);
  useEffect(() => {
    setRefColumnNames([]);
    if (!refTableInfo) return;
    let live = true;
    fetchTableColumns(refTableInfo.schema, refTableInfo.name)
      .then((c) => live && setRefColumnNames(c.map((x) => x.name)))
      .catch(() => {});
    return () => {
      live = false;
    };
  }, [refTableInfo]);

  const build = (): ConstraintSpec => {
    const n = name.trim() || undefined;
    if (kind === 'primary') return { type: 'primary', name: n, columns: cols };
    if (kind === 'unique') return { type: 'unique', name: n, columns: cols };
    if (kind === 'check') return { type: 'check', name: n, expression };
    return {
      type: 'foreign',
      name: n,
      columns: cols,
      refSchema: refTableInfo?.schema ?? '',
      refTable: refTableInfo?.name ?? '',
      refColumns: cols.map((_, i) => refCols[i] ?? ''),
      onDelete,
      onUpdate,
    };
  };
  const check = (() => {
    try {
      const spec = build();
      if (spec.type === 'foreign' && (!refTableInfo || spec.refColumns.some((c) => !c))) {
        return { spec, problem: 'Pick the referenced table and one column per local column' };
      }
      constraintSql(spec);
      return { spec, problem: null as string | null };
    } catch (err) {
      return { spec: null, problem: err instanceof DdlError ? err.message : String(err) };
    }
  })();
  const touched = cols.length > 0 || expression.trim() !== '';

  return (
    <DialogContent className="max-w-[500px]" data-testid="add-constraint-dialog">
      <DialogHeader>
        <DialogTitle>Add constraint</DialogTitle>
        <DialogDescription>
          On {schema}.{table}. Staged until you press Apply.
        </DialogDescription>
      </DialogHeader>
      <div className="grid grid-cols-2 gap-3">
        <div>
          <FieldLabel htmlFor="con-kind">Type</FieldLabel>
          <Select value={kind} onValueChange={(v) => setKind(v as ConstraintKind)}>
            <SelectTrigger id="con-kind" aria-label="Constraint type">
              <SelectValue />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="primary" disabled={hasPrimaryKey}>
                Primary key
              </SelectItem>
              <SelectItem value="unique">Unique</SelectItem>
              <SelectItem value="check">Check</SelectItem>
              <SelectItem value="foreign">Foreign key</SelectItem>
            </SelectContent>
          </Select>
        </div>
        <div>
          <FieldLabel htmlFor="con-name">Name (optional)</FieldLabel>
          <Input
            id="con-name"
            value={name}
            onChange={(e) => setName(e.target.value)}
            spellCheck={false}
          />
        </div>
      </div>
      {kind === 'check' ? (
        <div>
          <FieldLabel htmlFor="con-expr">Expression</FieldLabel>
          <Input
            id="con-expr"
            value={expression}
            onChange={(e) => setExpression(e.target.value)}
            placeholder="price >= 0"
            spellCheck={false}
            className="font-mono"
          />
        </div>
      ) : (
        <div>
          <FieldLabel>{kind === 'foreign' ? 'Local columns' : 'Columns'}</FieldLabel>
          <ColumnPicker columns={columns} value={cols} onChange={setCols} />
        </div>
      )}
      {kind === 'foreign' && (
        <>
          <div>
            <FieldLabel htmlFor="con-ref">References table</FieldLabel>
            <Select
              value={refTable}
              onValueChange={(v) => {
                setRefTable(v);
                setRefCols([]);
              }}
            >
              <SelectTrigger id="con-ref" aria-label="Referenced table">
                <SelectValue placeholder="Choose a table" />
              </SelectTrigger>
              <SelectContent>
                {tables.map((t) => (
                  <SelectItem key={`${t.schema}.${t.name}`} value={`${t.schema}.${t.name}`}>
                    {t.schema}.{t.name}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>
          {cols.length > 0 && refTableInfo && (
            <div className="grid grid-cols-[1fr_auto_1fr] items-center gap-x-2 gap-y-1.5">
              {cols.map((c, i) => (
                <div key={c} className="contents">
                  <span className="truncate font-mono text-[12px]">{c}</span>
                  <span className="text-[var(--wb-text-3)]">→</span>
                  <Select
                    value={refCols[i] ?? ''}
                    onValueChange={(v) => setRefCols((r) => Object.assign([...r], { [i]: v }))}
                  >
                    <SelectTrigger aria-label={`Referenced column for ${c}`}>
                      <SelectValue placeholder="column" />
                    </SelectTrigger>
                    <SelectContent>
                      {refColumnNames.map((rc) => (
                        <SelectItem key={rc} value={rc}>
                          {rc}
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </div>
              ))}
            </div>
          )}
          <div className="grid grid-cols-2 gap-3">
            {(
              [
                ['ON DELETE', onDelete, setOnDelete],
                ['ON UPDATE', onUpdate, setOnUpdate],
              ] as const
            ).map(([label, value, set]) => (
              <div key={label}>
                <FieldLabel>{label}</FieldLabel>
                <Select value={value} onValueChange={(v) => set(v as FkAction)}>
                  <SelectTrigger aria-label={label}>
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    {FK_ACTIONS.map((a) => (
                      <SelectItem key={a} value={a}>
                        {a}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>
            ))}
          </div>
        </>
      )}
      {touched && check.problem && <p className="text-[12px] text-destructive">{check.problem}</p>}
      <DialogFooter>
        <Button variant="secondary" onClick={onCancel}>
          Cancel
        </Button>
        <Button
          disabled={!check.spec || check.problem !== null}
          onClick={() => check.spec && onAdd(check.spec)}
          data-testid="add-constraint-submit"
        >
          Stage constraint
        </Button>
      </DialogFooter>
    </DialogContent>
  );
}
