/**
 * DDL for the table tab's Definition view (PF10).
 *
 * One catalog query returns tagged rows; `composeTableDdl` turns them into
 * a script. Views and materialized views use `pg_get_viewdef` (not a fake
 * CREATE TABLE); tables include identity / generated columns, constraints,
 * partition key, non-constraint indexes, triggers, comments, row-level
 * security and owner. Pure so it's unit-testable without a database.
 */
import { type BuiltSql, quoteIdent } from './table-query';

export type DdlRowKind =
  | 'rel'
  | 'viewdef'
  | 'partkey'
  | 'col'
  | 'con'
  | 'idx'
  | 'trg'
  | 'cmt'
  | 'ccmt';

/** Positional row shape: [kind, ord, a, b, c, d] — all text except ord. */
export type DdlRow = [
  DdlRowKind,
  number,
  string | null,
  string | null,
  string | null,
  string | null,
];

export function buildTableDdlSql(schema: string, table: string): BuiltSql {
  const sql = `
    WITH rel AS (
      SELECT c.oid, c.relkind::text AS relkind, c.relpersistence::text AS persistence,
             pg_catalog.pg_get_userbyid(c.relowner) AS owner,
             c.relrowsecurity, c.relforcerowsecurity
      FROM pg_catalog.pg_class c
      WHERE c.oid = $1::regclass
    )
    SELECT 'rel' AS kind, 0 AS ord, relkind AS a, owner AS b, persistence AS c,
           CASE WHEN relforcerowsecurity THEN 'force' WHEN relrowsecurity THEN 'on' ELSE '' END AS d
    FROM rel
    UNION ALL
    SELECT 'viewdef', 0, pg_catalog.pg_get_viewdef(rel.oid, true), NULL, NULL, NULL
    FROM rel WHERE relkind IN ('v', 'm')
    UNION ALL
    SELECT 'partkey', 0, pg_catalog.pg_get_partkeydef(rel.oid), NULL, NULL, NULL
    FROM rel WHERE relkind = 'p'
    UNION ALL
    SELECT 'col', a.attnum, a.attname,
           pg_catalog.format_type(a.atttypid, a.atttypmod),
           concat_ws(' ',
             CASE WHEN a.attcollation <> 0 AND a.attcollation <> t.typcollation
                  THEN 'COLLATE ' || quote_ident(co.collname) END,
             CASE a.attidentity WHEN 'a' THEN 'GENERATED ALWAYS AS IDENTITY'
                                WHEN 'd' THEN 'GENERATED BY DEFAULT AS IDENTITY' END,
             CASE WHEN a.attgenerated = 's'
                  THEN 'GENERATED ALWAYS AS (' || pg_catalog.pg_get_expr(d.adbin, d.adrelid) || ') STORED'
                  WHEN d.adbin IS NOT NULL
                  THEN 'DEFAULT ' || pg_catalog.pg_get_expr(d.adbin, d.adrelid) END,
             CASE WHEN a.attnotnull THEN 'NOT NULL' END),
           pg_catalog.col_description(rel.oid, a.attnum)
    FROM rel
    JOIN pg_catalog.pg_attribute a ON a.attrelid = rel.oid AND a.attnum > 0 AND NOT a.attisdropped
    JOIN pg_catalog.pg_type t ON t.oid = a.atttypid
    LEFT JOIN pg_catalog.pg_collation co ON co.oid = a.attcollation
    LEFT JOIN pg_catalog.pg_attrdef d ON d.adrelid = a.attrelid AND d.adnum = a.attnum
    UNION ALL
    SELECT 'con',
           CASE con.contype WHEN 'p' THEN 1 WHEN 'u' THEN 2 WHEN 'c' THEN 3 WHEN 'x' THEN 4 ELSE 5 END,
           con.conname, pg_catalog.pg_get_constraintdef(con.oid, true), con.contype::text, NULL
    FROM rel JOIN pg_catalog.pg_constraint con ON con.conrelid = rel.oid
    UNION ALL
    SELECT 'idx', 0, ic.relname, pg_catalog.pg_get_indexdef(i.indexrelid), NULL, NULL
    FROM rel
    JOIN pg_catalog.pg_index i ON i.indrelid = rel.oid
    JOIN pg_catalog.pg_class ic ON ic.oid = i.indexrelid
    WHERE NOT EXISTS (
      SELECT 1 FROM pg_catalog.pg_constraint k
      WHERE k.conrelid = rel.oid AND k.conindid = i.indexrelid
    )
    UNION ALL
    SELECT 'trg', 0, tg.tgname, pg_catalog.pg_get_triggerdef(tg.oid, true), NULL, NULL
    FROM rel JOIN pg_catalog.pg_trigger tg ON tg.tgrelid = rel.oid AND NOT tg.tgisinternal
    UNION ALL
    SELECT 'cmt', 0, pg_catalog.obj_description(rel.oid, 'pg_class'), NULL, NULL, NULL
    FROM rel WHERE pg_catalog.obj_description(rel.oid, 'pg_class') IS NOT NULL
    ORDER BY 1, 2, 3
  `;
  return { sql, params: [`${quoteIdent(schema)}.${quoteIdent(table)}`] };
}

function literal(text: string): string {
  return `'${text.replace(/'/g, "''")}'`;
}

function stripSemicolon(text: string): string {
  return text.replace(/;\s*$/, '').trimEnd();
}

/** Compose the DDL script from the rows of `buildTableDdlSql`. */
export function composeTableDdl(schema: string, table: string, rows: readonly unknown[][]): string {
  const typed = rows.map(
    (r) =>
      [
        String(r[0]) as DdlRowKind,
        Number(r[1]),
        r[2] == null ? null : String(r[2]),
        r[3] == null ? null : String(r[3]),
        r[4] == null ? null : String(r[4]),
        r[5] == null ? null : String(r[5]),
      ] as DdlRow,
  );
  const of = (kind: DdlRowKind) => typed.filter((r) => r[0] === kind);
  const rel = of('rel')[0];
  if (!rel) return `-- ${schema}.${table} was not found`;
  const [, , relkind, owner, persistence, rls] = rel;
  const ident = `${quoteIdent(schema)}.${quoteIdent(table)}`;
  const out: string[] = [];
  const cols = of('col').sort((a, b) => a[1] - b[1]);
  const isView = relkind === 'v';
  const isMatview = relkind === 'm';
  const objectWord = isView ? 'VIEW' : isMatview ? 'MATERIALIZED VIEW' : 'TABLE';

  if (isView || isMatview) {
    const def = stripSemicolon(of('viewdef')[0]?.[2] ?? '');
    out.push(
      isView
        ? `CREATE OR REPLACE VIEW ${ident} AS\n${def};`
        : `CREATE MATERIALIZED VIEW ${ident} AS\n${def}\nWITH DATA;`,
    );
  } else {
    const lines = cols.map(
      (c) => `  ${quoteIdent(c[2] ?? '')} ${c[3] ?? ''}${c[4] ? ` ${c[4]}` : ''}`,
    );
    const cons = of('con').sort((a, b) => a[1] - b[1] || String(a[2]).localeCompare(String(b[2])));
    for (const c of cons) lines.push(`  CONSTRAINT ${quoteIdent(c[2] ?? '')} ${c[3] ?? ''}`);
    const head =
      relkind === 'f'
        ? `CREATE FOREIGN TABLE ${ident}`
        : `CREATE ${persistence === 'u' ? 'UNLOGGED ' : ''}TABLE ${ident}`;
    const partkey = of('partkey')[0]?.[2];
    out.push(`${head} (\n${lines.join(',\n')}\n)${partkey ? `\nPARTITION BY ${partkey}` : ''};`);
  }

  const idx = of('idx').map((r) => `${stripSemicolon(r[3] ?? '')};`);
  if (idx.length > 0) out.push(idx.join('\n'));

  const trg = of('trg').map((r) => `${stripSemicolon(r[3] ?? '')};`);
  if (trg.length > 0) out.push(trg.join('\n'));

  const comments: string[] = [];
  const tableComment = of('cmt')[0]?.[2];
  if (tableComment) comments.push(`COMMENT ON ${objectWord} ${ident} IS ${literal(tableComment)};`);
  for (const c of cols) {
    if (c[5]) {
      comments.push(`COMMENT ON COLUMN ${ident}.${quoteIdent(c[2] ?? '')} IS ${literal(c[5])};`);
    }
  }
  if (comments.length > 0) out.push(comments.join('\n'));

  const tail: string[] = [];
  if (rls === 'on' || rls === 'force') tail.push(`ALTER TABLE ${ident} ENABLE ROW LEVEL SECURITY;`);
  if (rls === 'force') tail.push(`ALTER TABLE ${ident} FORCE ROW LEVEL SECURITY;`);
  if (owner) tail.push(`ALTER ${objectWord} ${ident} OWNER TO ${quoteIdent(owner)};`);
  if (tail.length > 0) out.push(tail.join('\n'));

  return `${out.join('\n\n')}\n`;
}
