#!/usr/bin/env node
/**
 * Rebuild native modules (better-sqlite3) against Electron's ABI after install.
 *
 * Runs automatically via the `postinstall` script in package.json so a local
 * `pnpm install` leaves a working dev environment.
 *
 * Skipped on CI: a bare `electron-rebuild` exits non-zero on the GitHub Actions
 * macOS runner (255) before the build starts. CI packaging instead rebuilds
 * native deps itself: electron-builder.yml sets `npmRebuild: true`, so
 * better-sqlite3 is rebuilt against each packaged target arch's Electron ABI
 * at package time (per-arch — one node_modules can't serve both macOS arches).
 */

import { spawnSync } from 'node:child_process'
import { existsSync, readFileSync } from 'node:fs'
import { createRequire } from 'node:module'
import { dirname, join } from 'node:path'

/**
 * pnpm doesn't always run electron's own install script (e.g. after the
 * version in the lockfile changes), leaving node_modules/electron without its
 * binary — `pnpm dev` then fails with "Electron uninstall". Download it here
 * when it's missing.
 */
function ensureElectronBinary() {
  let dir
  try {
    dir = dirname(createRequire(import.meta.url).resolve('electron/package.json'))
  } catch {
    return
  }
  const pathTxt = join(dir, 'path.txt')
  const binary = existsSync(pathTxt)
    ? join(dir, 'dist', readFileSync(pathTxt, 'utf8').trim())
    : null
  if (binary && existsSync(binary)) return
  console.log('[postinstall] Electron binary missing, downloading it')
  const r = spawnSync(process.execPath, [join(dir, 'install.js')], { stdio: 'inherit', cwd: dir })
  if (r.status !== 0) {
    console.error('[postinstall] Electron download failed; run `node node_modules/electron/install.js`')
    process.exit(r.status ?? 1)
  }
}

ensureElectronBinary()

if (process.env.CI) {
  console.log('[postinstall] CI detected, skipping electron-rebuild (CI runs `electron-builder install-app-deps` instead)')
  process.exit(0)
}

const result = spawnSync(
  process.platform === 'win32' ? 'npx.cmd' : 'npx',
  // NB: use -o/--only, not -w/--which-module — in @electron/rebuild 3.x, -w maps to
  // extraModules (modules *added* to the rebuild list), not a filter. Without -o the
  // rebuild also hits optional transitive natives like cpu-features (ssh2), whose gyp
  // build needs a file generated by its own install script, and fails.
  ['electron-rebuild', '-f', '-o', 'better-sqlite3'],
  { stdio: 'inherit' }
)
process.exit(result.status ?? 1)
