'use client';

import { useEffect, useRef } from 'react';

/**
 * Plasma oscilloscope — a live signal canvas. Draws a Lissajous-blended
 * sine wave on a tick-grid. The cursor warps the wave: closer pointer →
 * higher amplitude + chromatic split. Reduced motion = quiet flat line.
 *
 * No GPU. Pure 2D canvas, ~5kb of state. The whole hero atmosphere is
 * generated by this single component.
 */
export function Oscilloscope({
  variant = 'hero',
}: {
  variant?: 'hero' | 'rail' | 'minimal';
}) {
  const canvasRef = useRef<HTMLCanvasElement>(null);

  useEffect(() => {
    const canvas = canvasRef.current;
    if (!canvas) return;
    const ctx = canvas.getContext('2d');
    if (!ctx) return;
    const reduce = window.matchMedia('(prefers-reduced-motion: reduce)').matches;

    const dpr = Math.min(window.devicePixelRatio || 1, 2);
    let w = 0;
    let h = 0;
    const pointer = { x: -1000, y: -1000, has: false };
    let raf = 0;
    const t0 = performance.now();

    const resize = () => {
      const r = canvas.getBoundingClientRect();
      w = r.width;
      h = r.height;
      canvas.width = Math.floor(w * dpr);
      canvas.height = Math.floor(h * dpr);
      ctx.setTransform(dpr, 0, 0, dpr, 0, 0);
    };

    const onMove = (e: MouseEvent) => {
      const r = canvas.getBoundingClientRect();
      pointer.x = e.clientX - r.left;
      pointer.y = e.clientY - r.top;
      pointer.has = true;
    };

    const drawGrid = () => {
      const tick = variant === 'rail' ? 24 : 80;
      ctx.save();
      ctx.strokeStyle = 'rgba(233,236,232,0.05)';
      ctx.lineWidth = 1;
      ctx.beginPath();
      for (let x = 0; x <= w; x += tick) {
        ctx.moveTo(x + 0.5, 0);
        ctx.lineTo(x + 0.5, h);
      }
      for (let y = 0; y <= h; y += tick) {
        ctx.moveTo(0, y + 0.5);
        ctx.lineTo(w, y + 0.5);
      }
      ctx.stroke();
      ctx.restore();

      // Center crosshair (hero only)
      if (variant === 'hero') {
        ctx.save();
        ctx.strokeStyle = 'rgba(233,236,232,0.10)';
        ctx.setLineDash([2, 4]);
        ctx.beginPath();
        ctx.moveTo(0, h / 2);
        ctx.lineTo(w, h / 2);
        ctx.moveTo(w / 2, 0);
        ctx.lineTo(w / 2, h);
        ctx.stroke();
        ctx.restore();
      }
    };

    const drawWave = (now: number) => {
      const t = (now - t0) / 1000;
      const cy = h / 2;
      const baseAmp = variant === 'rail' ? h * 0.35 : h * 0.18;

      // Pointer-driven boost: closer = louder
      let boost = 0;
      if (pointer.has && !reduce) {
        const dx = Math.abs(pointer.x - w / 2);
        const dy = Math.abs(pointer.y - cy);
        const reach = Math.min(w, h) * 0.6;
        const dist = Math.sqrt(dx * dx + dy * dy);
        boost = Math.max(0, 1 - dist / reach) * baseAmp * 1.4;
      }
      const amp = reduce ? baseAmp * 0.25 : baseAmp + boost;

      const lobes = 3.2;
      const speed = reduce ? 0 : 1.2;
      const k = (Math.PI * 2 * lobes) / w;

      // Three offset traces — chromatic split.
      // Mono-pink, matching app brand. Center = exact Plasma pink, outers
      // are darker/lighter shades for the chromatic-aberration feel.
      const traces: [string, number, number][] = [
        ['rgba(220, 105, 92, 0.45)', -2, 0.85],
        ['rgba(247, 131, 116, 0.95)', 0, 1],
        ['rgba(255, 168, 156, 0.45)', 2, 0.85],
      ];

      for (const [color, offset, scale] of traces) {
        ctx.save();
        ctx.strokeStyle = color;
        ctx.lineWidth = offset === 0 ? 1.4 : 1;
        ctx.shadowColor = color;
        ctx.shadowBlur = offset === 0 ? 14 : 0;
        ctx.beginPath();
        for (let x = 0; x <= w; x += 2) {
          const px = x + offset;
          const phase = t * speed + px * 0.0035;
          const y =
            cy +
            Math.sin(px * k + phase) * amp * scale +
            Math.sin(px * k * 0.41 + phase * 1.4) * amp * 0.35 * scale +
            Math.cos(px * k * 0.21 - phase * 0.6) * amp * 0.18 * scale;
          if (x === 0) ctx.moveTo(px, y);
          else ctx.lineTo(px, y);
        }
        ctx.stroke();
        ctx.restore();
      }

      // Pointer pulse marker
      if (pointer.has && !reduce && variant === 'hero') {
        const r = 6 + Math.sin(t * 6) * 2;
        ctx.save();
        ctx.fillStyle = 'rgba(247, 131, 116, 0.95)';
        ctx.shadowColor = 'rgba(247, 131, 116, 1)';
        ctx.shadowBlur = 18;
        ctx.beginPath();
        ctx.arc(pointer.x, pointer.y, r, 0, Math.PI * 2);
        ctx.fill();
        ctx.restore();
      }
    };

    let visible = true;
    const tick = (now: number) => {
      if (visible) {
        ctx.clearRect(0, 0, w, h);
        drawGrid();
        drawWave(now);
      }
      raf = requestAnimationFrame(tick);
    };

    resize();
    const ro = new ResizeObserver(resize);
    ro.observe(canvas);
    // Pause draw work when off-screen — avoids two oscilloscopes
    // (hero + open) chewing the CPU at the same time on long pages.
    const io = new IntersectionObserver(
      (entries) => {
        for (const e of entries) visible = e.isIntersecting;
      },
      { threshold: 0 },
    );
    io.observe(canvas);
    window.addEventListener('mousemove', onMove);
    raf = requestAnimationFrame(tick);

    return () => {
      cancelAnimationFrame(raf);
      ro.disconnect();
      io.disconnect();
      window.removeEventListener('mousemove', onMove);
    };
  }, [variant]);

  return (
    <canvas
      ref={canvasRef}
      aria-hidden
      className="absolute inset-0 z-0 h-full w-full pointer-events-none"
    />
  );
}
